export const CITY_CAM_INFO = {
    london: { label: 'London', liveApi: '/api/cameras/london', external: 'https://www.earthcam.com/world/england/london/' },
    singapore: { label: 'Singapore', liveApi: '/api/cameras/singapore', external: 'https://onemotoring.lta.gov.sg/content/onemotoring/home/driving/traffic_information/traffic-cameras.html' },
    nyc: { label: 'New York', staticApi: '/api/cameras/static/nyc', external: 'https://webcams.nyc.gov/' },
    la: { label: 'Los Angeles', staticApi: '/api/cameras/static/la', external: 'https://cwwp2.dot.ca.gov/vm/streamlist.htm' },
    chicago: { label: 'Chicago', staticApi: '/api/cameras/static/chicago', external: 'https://www.earthcam.com/usa/illinois/chicago/' },
    miami: { label: 'Miami', staticApi: '/api/cameras/static/miami', external: 'https://www.earthcam.com/usa/florida/miami/' },
    dc: { label: 'Washington DC', staticApi: '/api/cameras/static/dc', external: 'https://www.earthcam.com/usa/dc/washingtondc/' },
    toronto: { label: 'Toronto', staticApi: '/api/cameras/static/toronto', external: 'https://www.earthcam.com/world/canada/toronto/' },
    vancouver: { label: 'Vancouver', staticApi: '/api/cameras/static/vancouver', external: 'https://www.earthcam.com/world/canada/vancouver/' },
    mexico: { label: 'Mexico City', staticApi: '/api/cameras/static/mexico', external: 'https://www.earthcam.com/world/mexico/mexicocity/' },
    saopaulo: { label: 'Sao Paulo', staticApi: '/api/cameras/static/saopaulo', external: 'https://www.earthcam.com/world/brazil/saopaulo/' },
    buenosaires: { label: 'Buenos Aires', staticApi: '/api/cameras/static/buenosaires', external: 'https://www.earthcam.com/world/argentina/buenosaires/' },
    bogota: { label: 'Bogota', staticApi: '/api/cameras/static/bogota', external: 'https://www.earthcam.com/world/colombia/bogota/' },
    lima: { label: 'Lima', staticApi: '/api/cameras/static/lima', external: 'https://www.earthcam.com/world/peru/lima/' },
    santiago: { label: 'Santiago', staticApi: '/api/cameras/static/santiago', external: 'https://www.earthcam.com/world/chile/santiago/' },
    paris: { label: 'Paris', staticApi: '/api/cameras/static/paris', external: 'https://www.earthcam.com/world/france/paris/' },
    berlin: { label: 'Berlin', staticApi: '/api/cameras/static/berlin', external: 'https://www.earthcam.com/world/germany/berlin/' },
    madrid: { label: 'Madrid', staticApi: '/api/cameras/static/madrid', external: 'https://www.earthcam.com/world/spain/madrid/' },
    rome: { label: 'Rome', staticApi: '/api/cameras/static/rome', external: 'https://www.earthcam.com/world/italy/rome/' },
    amsterdam: { label: 'Amsterdam', staticApi: '/api/cameras/static/amsterdam', external: 'https://www.earthcam.com/world/netherlands/amsterdam/' },
    brussels: { label: 'Brussels', staticApi: '/api/cameras/static/brussels', external: 'https://www.earthcam.com/world/belgium/brussels/' },
    vienna: { label: 'Vienna', staticApi: '/api/cameras/static/vienna', external: 'https://www.earthcam.com/world/austria/vienna/' },
    warsaw: { label: 'Warsaw', staticApi: '/api/cameras/static/warsaw', external: 'https://www.earthcam.com/world/poland/warsaw/' },
    kyiv: { label: 'Kyiv', staticApi: '/api/cameras/static/kyiv', external: 'https://www.earthcam.com/world/ukraine/kyiv/' },
    moscow: { label: 'Moscow', staticApi: '/api/cameras/static/moscow', external: 'https://www.earthcam.com/world/russia/moscow/' },
    stockholm: { label: 'Stockholm', staticApi: '/api/cameras/static/stockholm', external: 'https://www.earthcam.com/world/sweden/stockholm/' },
    lisbon: { label: 'Lisbon', staticApi: '/api/cameras/static/lisbon', external: 'https://www.earthcam.com/world/portugal/lisbon/' },
    athens: { label: 'Athens', staticApi: '/api/cameras/static/athens', external: 'https://www.earthcam.com/world/greece/athens/' },
    istanbul: { label: 'Istanbul', staticApi: '/api/cameras/static/istanbul', external: 'https://www.earthcam.com/world/turkey/istanbul/' },
    dubai: { label: 'Dubai', staticApi: '/api/cameras/static/dubai', external: 'https://www.earthcam.com/world/unitedarabemirates/dubai/' },
    abudhabi: { label: 'Abu Dhabi', staticApi: '/api/cameras/static/abudhabi', external: 'https://www.earthcam.com/world/unitedarabemirates/' },
    riyadh: { label: 'Riyadh', staticApi: '/api/cameras/static/riyadh', external: 'https://www.earthcam.com/world/saudiarabia/' },
    baghdad: { label: 'Baghdad', staticApi: '/api/cameras/static/baghdad', external: 'https://www.google.com/search?q=Baghdad+live+cameras' },
    tehran: { label: 'Tehran', staticApi: '/api/cameras/static/tehran', external: 'https://www.earthcam.com/world/iran/tehran/' },
    doha: { label: 'Doha', staticApi: '/api/cameras/static/doha', external: 'https://www.earthcam.com/world/qatar/doha/' },
    kuwait: { label: 'Kuwait City', staticApi: '/api/cameras/static/kuwait', external: 'https://www.google.com/search?q=Kuwait+City+live+cameras' },
    muscat: { label: 'Muscat', staticApi: '/api/cameras/static/muscat', external: 'https://www.google.com/search?q=Muscat+live+cameras' },
    beirut: { label: 'Beirut', staticApi: '/api/cameras/static/beirut', external: 'https://www.earthcam.com/world/lebanon/beirut/' },
    amman: { label: 'Amman', staticApi: '/api/cameras/static/amman', external: 'https://www.google.com/search?q=Amman+live+cameras' },
    telaviv: { label: 'Tel Aviv', staticApi: '/api/cameras/static/telaviv', external: 'https://www.earthcam.com/world/israel/telaviv/' },
    cairo: { label: 'Cairo', staticApi: '/api/cameras/static/cairo', external: 'https://www.earthcam.com/world/egypt/cairo/' },
    lagos: { label: 'Lagos', staticApi: '/api/cameras/static/lagos', external: 'https://www.earthcam.com/world/nigeria/lagos/' },
    nairobi: { label: 'Nairobi', staticApi: '/api/cameras/static/nairobi', external: 'https://www.earthcam.com/world/kenya/nairobi/' },
    joburg: { label: 'Johannesburg', staticApi: '/api/cameras/static/joburg', external: 'https://www.earthcam.com/world/southafrica/' },
    addis: { label: 'Addis Ababa', staticApi: '/api/cameras/static/addis', external: 'https://www.google.com/search?q=Addis+Ababa+live+cameras' },
    casablanca: { label: 'Casablanca', staticApi: '/api/cameras/static/casablanca', external: 'https://www.earthcam.com/world/morocco/casablanca/' },
    khartoum: { label: 'Khartoum', staticApi: '/api/cameras/static/khartoum', external: 'https://www.google.com/search?q=Khartoum+live+cameras' },
    kinshasa: { label: 'Kinshasa', staticApi: '/api/cameras/static/kinshasa', external: 'https://www.google.com/search?q=Kinshasa+live+cameras' },
    tokyo: { label: 'Tokyo', staticApi: '/api/cameras/static/tokyo', external: 'https://www.earthcam.com/world/japan/tokyo/' },
    beijing: { label: 'Beijing', staticApi: '/api/cameras/static/beijing', external: 'https://www.earthcam.com/world/china/beijing/' },
    shanghai: { label: 'Shanghai', staticApi: '/api/cameras/static/shanghai', external: 'https://www.earthcam.com/world/china/shanghai/' },
    seoul: { label: 'Seoul', staticApi: '/api/cameras/static/seoul', external: 'https://www.earthcam.com/world/korea/seoul/' },
    hongkong: { label: 'Hong Kong', staticApi: '/api/cameras/static/hongkong', external: 'https://www.earthcam.com/world/china/hongkong/' },
    bangkok: { label: 'Bangkok', staticApi: '/api/cameras/static/bangkok', external: 'https://www.earthcam.com/world/thailand/bangkok/' },
    jakarta: { label: 'Jakarta', staticApi: '/api/cameras/static/jakarta', external: 'https://www.earthcam.com/world/indonesia/jakarta/' },
    kl: { label: 'Kuala Lumpur', staticApi: '/api/cameras/static/kl', external: 'https://www.earthcam.com/world/malaysia/kualalumpur/' },
    manila: { label: 'Manila', staticApi: '/api/cameras/static/manila', external: 'https://www.earthcam.com/world/philippines/manila/' },
    hcmc: { label: 'Ho Chi Minh', staticApi: '/api/cameras/static/hcmc', external: 'https://www.earthcam.com/world/vietnam/hochiminhcity/' },
    sydney: { label: 'Sydney', staticApi: '/api/cameras/static/sydney', external: 'https://www.livetraffic.com/traffic-cameras.html' },
    melbourne: { label: 'Melbourne', staticApi: '/api/cameras/static/melbourne', external: 'https://www.earthcam.com/world/australia/melbourne/' },
    delhi: { label: 'Delhi', staticApi: '/api/cameras/static/delhi', external: 'https://www.earthcam.com/world/india/newdelhi/' },
    mumbai: { label: 'Mumbai', staticApi: '/api/cameras/static/mumbai', external: 'https://www.earthcam.com/world/india/mumbai/' },
    karachi: { label: 'Karachi', staticApi: '/api/cameras/static/karachi', external: 'https://www.google.com/search?q=Karachi+live+cameras' },
    dhaka: { label: 'Dhaka', staticApi: '/api/cameras/static/dhaka', external: 'https://www.google.com/search?q=Dhaka+live+cameras' },
    colombo: { label: 'Colombo', staticApi: '/api/cameras/static/colombo', external: 'https://www.google.com/search?q=Colombo+live+cameras' },
  };
export function getCityCamInfo(city) {
    if (CITY_CAM_INFO[city.cam]) return CITY_CAM_INFO[city.cam];
    const query = city.country === 'US'
      ? `${city.name} traffic cameras live`
      : `${city.name} live webcam CCTV street camera`;
    return {
      label: city.name,
      windRadius: city.country === 'US' ? 90 : 60,
      external: `https://www.google.com/search?q=${encodeURIComponent(query)}`,
    };
  }


